/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  k8sSidebar: [
    {
      type: 'autogenerated',
      dirName: 'k8s', // 从 docs/k8s 目录自动生成
    },
  ],
  
  prometheusSidebar: [
    {
      type: 'autogenerated',
      dirName: 'monitoring', // 从 docs/monitoring 目录自动生成
    },
  ],
  
  databaseSidebar: [
    {
      type: 'autogenerated',
      dirName: 'database', // 从 docs/database 目录自动生成
    },
  ],
  
  programmingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'programming', // 从 docs/programming 目录自动生成
    },
  ],
};

export default sidebars;
